name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Trim commit SHA
        shell: bash
        run: 
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    needs: ci
    steps:

      - uses: actions/checkout@v4
    
      - name: Update values yaml file
        shell: bash
        run: |
          sed -i "s/tag: .*/tag: ${{ needs.ci.outputs.commit_id }}/" charts/python-app/values.yaml

      - name: Commit changes to values yaml file
        shell: EndBug/add-and-commit@v9
        with:
          add: charts/python-app/values.yaml
          message: "Update values yaml file with commit id ${{ needs.ci.outputs.commit_id }}"
          push: true

      - name: ArgoCD installation
        shell: bash
        run: |
          curl -sSL -o argocd "https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64"
          ls
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
       
      - name: ArgoCD App Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd --insecure --grpc-web --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
          argocd app wait python-app --health